import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
                <link rel="shortcut icon" href="./assets/images/favicon.ico" />
                {/* <link href="./assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" /> */}
                {/* <link href="./assets/css/icons.min.css" rel="stylesheet" type="text/css" /> */}
                {/* <link href="./assets/css/app.min.css" rel="stylesheet" type="text/css" /> */}
                {/* <link rel="stylesheet" href="./assets/css/style.css" /> */}
                <link rel="stylesheet" href="./assets/css/style.css" />

    </head>
      <body>
        {children}
      </body>
    </html>
  );
}
